// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.30.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class WrappedChat {
  final String conversationId;
  String chatName;
  final String tone;
  final String updateTimeLocal;
  final List<String> plugins;

  WrappedChat({
    required this.conversationId,
    required this.chatName,
    required this.tone,
    required this.updateTimeLocal,
    required this.plugins,
  });

  @override
  int get hashCode =>
      conversationId.hashCode ^
      chatName.hashCode ^
      tone.hashCode ^
      updateTimeLocal.hashCode ^
      plugins.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WrappedChat &&
          runtimeType == other.runtimeType &&
          conversationId == other.conversationId &&
          chatName == other.chatName &&
          tone == other.tone &&
          updateTimeLocal == other.updateTimeLocal &&
          plugins == other.plugins;
}

class WrappedMsg {
  final String author;
  final String text;

  const WrappedMsg({
    required this.author,
    required this.text,
  });

  @override
  int get hashCode => author.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WrappedMsg &&
          runtimeType == other.runtimeType &&
          author == other.author &&
          text == other.text;
}
