// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.30.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String generateUuidv4String({dynamic hint}) =>
    RustLib.instance.api.generateUuidv4String(hint: hint);

String readFile({required String path, dynamic hint}) =>
    RustLib.instance.api.readFile(path: path, hint: hint);

Future<String> genTimeLocal({int? time, dynamic hint}) =>
    RustLib.instance.api.genTimeLocal(time: time, hint: hint);
